-- 0030 -- separate the contractual note rate from the disclosed APR.
--
-- PR #10 review, high. Making `compute_apr` return the true actuarial APR
-- changed what `offers.apr` MEANS without changing who reads it. Origination's
-- accept path takes `offers.apr` as `rate` and hands it to
-- `board_to_servicing_tx`, which writes it to `loans.apr`; servicing then
-- amortizes the loan at that value
-- (`servicing-service/app/routers/loans.py::loan_schedule`).
--
-- Before the APR fix that was already wrong -- it amortized at the old add-on
-- ratio, 5.196%, and produced payments BELOW the disclosed 439.35. The APR fix
-- flipped the error to 9.584%, which produces 452.94, i.e. a borrower billed
-- MORE per month than the disclosure they signed. Same defect, worse direction:
-- 13.59 a month, 652 over a 48-month term.
--
-- The two numbers are not interchangeable and never were:
--
--   note rate  -- what the payment schedule is calculated on. 7.99%.
--   APR        -- the all-in cost solved against the amount financed, which is
--                 higher than the note rate whenever a prepaid fee exists.
--
-- So `offers.apr` keeps its correct new meaning (the disclosed APR, which is
-- what Reg Z requires on the disclosure) and the contractual rate gets its own
-- column, which is what boarding reads.

ALTER TABLE offers
    ADD COLUMN IF NOT EXISTS note_rate_pct NUMERIC(7,3);

-- Back-fill. Every offer this system has ever written was built at a single
-- hard-coded 7.99% -- it was a literal in disclosure-service's create_offer and
-- there has never been a second value, so this is recovering a known constant
-- rather than guessing a rate per row. (It is now
-- `disclosure-service/app/fees.py::NOTE_RATE_PCT`, for the same
-- one-source-of-truth reason the origination fee was consolidated after D6.)
--
-- Deliberately NOT derived from each row's stored payment: solving the rate per
-- row would be more impressive and less honest, since it would silently invent
-- plausible per-row rates for any row whose payment was itself written wrong.
UPDATE offers SET note_rate_pct = 7.99 WHERE note_rate_pct IS NULL;

DO $$
DECLARE
    unset_rows INTEGER;
BEGIN
    SELECT count(*) INTO unset_rows FROM offers WHERE note_rate_pct IS NULL;
    IF unset_rows = 0 THEN
        RAISE NOTICE '0030: every offer now records the note rate it was written at.';
    ELSE
        RAISE WARNING '0030: % offer(s) still have no note_rate_pct -- accept will refuse to board them.', unset_rows;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Contractual payment schedule, persisted as fact (Model B)
-- ---------------------------------------------------------------------------
-- Extends this migration rather than adding a new one. 0030 is unmerged and has
-- never been deployed anywhere (it exists only on kalab-actuarial-apr-fix), and
-- 0031 is already taken by PR #15's DROP COLUMN. Adding 0032 while 0031 is still
-- open would land a HIGHER number first and then a lower one, which
-- version-tracked replay cannot express safely. The note-rate correction and the
-- schedule-fact correction are also one semantic change: both exist because the
-- disclosed APR and the contractual terms were being conflated.
--
-- WHY PERSIST THE SCHEDULE AT ALL
-- The read path used to rebuild it: principal recovered as
-- amount_financed / (1 - fee_pct), term as total_of_payments / monthly_payment,
-- then the schedule regenerated by whatever generator was deployed at read time.
-- So an accepted disclosure was not a stored fact -- a later rounding-policy or
-- fee change silently re-derived different contractual terms for a loan somebody
-- had already signed. Under Model B the final payment differs from the regular
-- one, and it cannot be recovered from any stored figure at all.
--
-- schedule_version identifies the rounding policy that produced the row, so a
-- future policy change is distinguishable rather than retroactive. 'B1' is
-- level cent-rounded regular payments with the final period billing remaining
-- principal plus that period's interest.

ALTER TABLE offers
    ADD COLUMN IF NOT EXISTS regular_payment_count INTEGER,
    ADD COLUMN IF NOT EXISTS final_payment         NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS term_months           INTEGER,
    ADD COLUMN IF NOT EXISTS schedule_version      TEXT;

-- The contract as boarded. Servicing must bill these amounts, not recompute them
-- from principal/rate/term -- that recomputation is exactly what would drift.
ALTER TABLE loans
    ADD COLUMN IF NOT EXISTS regular_payment       NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS regular_payment_count INTEGER,
    ADD COLUMN IF NOT EXISTS final_payment         NUMERIC(14,2),
    ADD COLUMN IF NOT EXISTS schedule_version      TEXT;

-- Deliberately NO back-fill for any of the above.
--
-- The exact contractual schedule of an already-accepted historical offer was
-- never stored. Reconstructing it with today's generator would persist invented
-- terms as though they were the agreed ones -- the same defect as the read-path
-- regeneration, made permanent. NULL means "not recorded", which is a true
-- statement, and the code treats it as such:
--
--   * new offers always store the complete schedule;
--   * an UNACCEPTED legacy offer missing schedule terms cannot board (it can be
--     regenerated through the audited repair path instead);
--   * an ACCEPTED legacy offer stays immutable, still displays its stored
--     four-box disclosure, and reports the detailed schedule as unavailable
--     rather than regenerating it.
--
-- Contrast with note_rate_pct above, which IS back-filled: every offer this
-- system ever wrote used a single hard-coded 7.99%, so that recovers a known
-- constant. No such constant exists for a per-row final payment.

DO $$
DECLARE
    unpinned INTEGER;
BEGIN
    SELECT count(*) INTO unpinned FROM offers WHERE final_payment IS NULL;
    IF unpinned > 0 THEN
        RAISE NOTICE
          '0030: % offer(s) have no stored payment schedule (legacy). They keep '
          'their four-box disclosure; boarding refuses them and the detailed '
          'schedule reports as unavailable.', unpinned;
    END IF;
END $$;
