"""disclosure-service's schedule generator, pinned to the literal golden vectors.

The generator is implemented three times -- disclosure-service,
origination-service and servicing-service each carry their own
`app/schedule.py`. They cannot import a shared module: separate images, no
shared internal package (ADR 0004 records how the copies arose). Three
independent implementations of regulated money math will drift, and the drift
is invisible until a borrower is billed something a disclosure never said.

This file is one of three identical parity tests, one per service, all reading
the SAME literal data file: db/golden/model_b_schedule_vectors.json. Identical
on purpose -- a divergence between the copies has to fail in the suite of the
copy that changed, so the failure names the service.

The vectors are checked-in literals verified by hand, not values regenerated by
db/tools/golden_schedule_vectors.py. A test comparing this service against that
script would prove only that two pieces of code agree; if the shared
understanding of Model B were wrong, both would agree on the wrong answer.

This service OWNS the disclosure, so a drift here changes what a borrower
is told rather than what a report displays. The derived monetary figures
and the APR are checked in test_apr.py / test_offer.py against the same
golden file.

The golden APR values are this system's own solve. No outside oracle has
confirmed them -- the FFIEC check is still outstanding -- so they pin the
solver against change and are not evidence of correctness.
"""
import json
from decimal import Decimal
from pathlib import Path

import pytest

from app import schedule

_GOLDEN = (
    Path(__file__).resolve().parents[3] / "db" / "golden" / "model_b_schedule_vectors.json"
)
# parse_float=Decimal (D1): the schedule rows are Decimal to the serializer
# boundary now, and comparing them against JSON-parsed binary floats would fail
# on values that are equal in cents -- Decimal("366.12") != 366.12 as a float.
# Parsing the golden vectors as Decimal makes the comparison EXACT rather than
# float-tolerant, which is stricter than what this test did before.
_VECTORS = json.loads(_GOLDEN.read_text(), parse_float=Decimal)["vectors"]
_NAMES = sorted(_VECTORS)


def _rows(name):
    v = _VECTORS[name]
    return v, schedule.amortization(v["principal"], v["note_rate_pct"], v["term_months"])


@pytest.mark.parametrize("name", _NAMES)
def test_the_regular_payment_matches_the_golden_vector(name):
    """Every non-final period bills this exact amount.

    BOARDING-24 is the case that matters most: its exact level payment is
    407.004576918..., so a generator that rounded the wrong way would produce
    407.01 and overbill by a cent in each of 23 periods.
    """
    v, rows = _rows(name)
    for row in rows[:-1]:
        assert row["payment"] == v["regular_payment"], (
            f"{name}: period {row['n']} bills {row['payment']}, "
            f"golden says {v['regular_payment']}"
        )


@pytest.mark.parametrize("name", _NAMES)
def test_the_regular_payment_count_matches_the_golden_vector(name):
    """term_months - 1 regular payments, which is also what
    offers_schedule_term_agrees enforces in the database."""
    v, rows = _rows(name)
    assert len(rows) - 1 == v["regular_payment_count"]
    assert len(rows) == v["term_months"]


@pytest.mark.parametrize("name", _NAMES)
def test_the_final_payment_matches_the_golden_vector(name):
    """The adjusted final payment -- the value that cannot be recovered from any
    other stored figure, which is the whole reason it is persisted.

    RV-2-36's final payment is LOWER than its regular one while LIVE-48's is
    higher, so an implementation that assumed the adjustment always rounds one
    direction fails on exactly one of these vectors.
    """
    v, rows = _rows(name)
    assert rows[-1]["payment"] == v["final_payment"]


@pytest.mark.parametrize("name", _NAMES)
def test_the_total_of_payments_matches_the_golden_vector(name):
    """The SUM OF ACTUAL PAYMENTS. The original defect derived the total from
    the unrounded payment times the term, which disagreed with the schedule it
    was printed beside by 0.16 on a regulated figure."""
    v, rows = _rows(name)
    total = round(sum(r["payment"] for r in rows), 2)
    assert total == v["total_of_payments"]
    # And the identity the literals were hand-checked against.
    assert total == round(
        v["regular_payment"] * v["regular_payment_count"] + v["final_payment"], 2
    )


@pytest.mark.parametrize("name", _NAMES)
def test_the_first_and_final_rows_match_the_golden_vector(name):
    """Full row detail at both ends: the interest split, the principal
    component and the running balance, not just the payment. A generator can
    bill the right amount and still apportion it wrongly."""
    v, rows = _rows(name)
    for label, actual, expected in (
        ("first", rows[0], v["first_row"]),
        ("final", rows[-1], v["final_row"]),
    ):
        for field in ("payment", "principal", "interest", "balance"):
            assert actual[field] == expected[field], (
                f"{name}: {label} row {field} is {actual[field]}, "
                f"golden says {expected[field]}"
            )


@pytest.mark.parametrize("name", _NAMES)
def test_every_row_is_internally_consistent(name):
    """payment == principal + interest, in every period. Model B moves the
    residue into the final PAYMENT rather than into a principal column, so this
    holds on the last row too -- which is precisely what distinguishes it from
    the model that hid the residue."""
    _, rows = _rows(name)
    for row in rows:
        assert round(row["principal"] + row["interest"], 2) == row["payment"], (
            f"{name}: period {row['n']} does not foot"
        )


@pytest.mark.parametrize("name", _NAMES)
def test_the_principal_components_retire_the_principal_exactly(name):
    """No cent invented and none lost across the whole schedule."""
    v, rows = _rows(name)
    assert round(sum(r["principal"] for r in rows), 2) == v["principal"]
    assert rows[-1]["balance"] == 0.0


@pytest.mark.parametrize("name", _NAMES)
def test_the_balance_never_goes_negative(name):
    """An overshoot would mean the borrower was billed past the payoff."""
    _, rows = _rows(name)
    for row in rows:
        assert row["balance"] >= 0.0, f"{name}: period {row['n']} overshot"


def test_the_zero_rate_vector_charges_no_interest_at_all():
    """The zero-rate branch exists because the amortization formula divides by
    zero at a zero monthly rate. Named explicitly rather than left to the
    parametrized cases, since it is the only vector that exercises it."""
    v, rows = _rows("ZERO-RATE-36")
    assert v["note_rate_pct"] == 0.0
    assert all(r["interest"] == 0.0 for r in rows)
    assert round(sum(r["payment"] for r in rows), 2) == v["principal"]


def test_the_golden_file_is_the_one_shared_source():
    """A copy of this file drifting to its own private literals would defeat
    the point, so the path is asserted rather than merely used."""
    assert _GOLDEN.is_file(), f"golden vectors not found at {_GOLDEN}"
    assert _GOLDEN.parts[-3:] == ("db", "golden", "model_b_schedule_vectors.json")
    assert len(_NAMES) == 5, "the five named vectors are the agreed set"
