"""A retry must be safe, and a retry must be *authorised*. Those are two things.

**The first defect.** Intake commits the applicant and application rows and then
calls kyc-service. On a failure it returned a bare 503 -- no identifier, no token --
and said "please retry". A retry created a SECOND applicant and a SECOND
application. One person, two borrower records.

**The defect that fix introduced, which is worse.** The idempotency key became the
thing that recovered an application: present the key, receive a fresh access
token. A client-chosen key is not a secret -- it travels in request bodies, proxy
logs and client-side code, and it can be guessed. Anyone holding one could obtain
a live access token and from there request a decision, read the application and
trigger a credit pull. **Application takeover, through the path added to make
retries safe.**

The reasoning was written into the docstring: *"it is safe because the caller has
just proved it owns this application by presenting the key that created it."*
Presenting an identifier is not proof of ownership.

So the contract these tests pin:

**The third defect, and why rotation is gone.** The fix above generated the
resume token on the SERVER and returned it in the response. A client whose
response is lost -- gateway timeout, closed tab, dropped connection -- therefore
never receives the credential it is later required to present. It retries with
the key alone and is refused. The applicant is locked out of their own in-flight
application and starts over, creating the duplicate the key was added to
prevent. Rotation made this strictly worse: it re-armed the same trap on every
subsequent attempt.

So the credential is now generated by the CLIENT before the first request and
sent on every submission including that first one.

- the **key** says *which* application a retry belongs to;
- the **resume secret** -- client-generated, sent with the first request, stored
  only as a sha256 hash -- says the caller may recover it;
- **both** are required, and failure is indistinguishable across missing, wrong
  and expired;
- the secret is **stable** for the life of the draft and bounded by expiry. It is
  deliberately NOT rotated: handing back a new one on each recovery would rebuild
  the lost-response hole one attempt later. The trade is that a stolen secret
  stays valid until the draft expires -- the ordinary property of a bearer
  credential -- while the **access token**, which is what authorises decisioning,
  still rotates on every recovery.

Against real PostgreSQL: the guarantees are a partial unique index, a transaction
boundary and a constant-time hash comparison. None of that is observable in a mock.
"""
import os
import pathlib
import uuid

import psycopg2
import psycopg2.extras
import pytest

DATABASE_URL = os.getenv("DATABASE_URL")
pytestmark = pytest.mark.skipif(
    not DATABASE_URL, reason="DATABASE_URL not set -- no Postgres to test against"
)

REPO = pathlib.Path(__file__).resolve().parents[3]
SCHEMA = "intake_retry_test"
INIT = REPO / "db" / "init"


@pytest.fixture
def db(monkeypatch):
    from app import config, database
    from app import db as app_db

    conn = psycopg2.connect(DATABASE_URL)
    conn.autocommit = True
    with conn.cursor() as cur:
        cur.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE")
        cur.execute(f"CREATE SCHEMA {SCHEMA}")
    with conn.cursor() as cur:
        cur.execute(f"SET search_path TO {SCHEMA}")
        cur.execute((INIT / "001_schema.sql").read_text(encoding="utf-8"))

    scoped = f"{DATABASE_URL}?options=-csearch_path%3D{SCHEMA}"
    monkeypatch.setattr(app_db, "DATABASE_URL", scoped, raising=False)
    monkeypatch.setattr(app_db, "_conn", None, raising=False)
    monkeypatch.setattr(config, "DATABASE_URL", scoped, raising=False)
    monkeypatch.setattr(database, "DATABASE_URL", scoped, raising=False)
    monkeypatch.setattr(database, "_engine", None, raising=False)
    monkeypatch.setattr(database, "_Session", None, raising=False)
    yield conn
    with conn.cursor() as cur:
        cur.execute(f"DROP SCHEMA IF EXISTS {SCHEMA} CASCADE")
    conn.close()
    monkeypatch.setattr(app_db, "_conn", None, raising=False)


def _count(conn, table):
    with conn.cursor() as cur:
        cur.execute(f"SET search_path TO {SCHEMA}")
        cur.execute(f"SELECT count(*) FROM {table}")
        return cur.fetchone()[0]


def _row(conn, app_id):
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(f"SET search_path TO {SCHEMA}")
        cur.execute("SELECT * FROM applications WHERE id = %s", (app_id,))
        return cur.fetchone()


def _query(conn, sql, params):
    with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
        cur.execute(f"SET search_path TO {SCHEMA}")
        cur.execute(sql, params)
        return cur.fetchall()


def _payload(key):
    return {
        "idempotency_key": key,
        "name": "Robin Fictional", "dob": "1985-02-11", "ssn": "999-00-0042",
        "address": "1 Test Street", "zip_code": "99301",
        "email": "robin@example.test", "phone": "5550101234",
        "amount": 9000, "term_months": 24, "income": 60000,
    }


# --- the original guarantee still holds --------------------------------------

def test_a_retry_with_the_token_creates_exactly_one_applicant_and_application(db):
    from app import intake

    key = f"retry-{uuid.uuid4()}"
    secret = f"client-{uuid.uuid4()}"
    app_id, _, resume = intake.create_application(_payload(key), resume_token=secret)
    again_id, _, resume2 = intake.create_application(_payload(key), resume_token=secret)

    assert again_id == app_id
    assert _count(db, "applicants") == 1, "the retry created a second applicant"
    assert _count(db, "applications") == 1
    assert resume == resume2 == secret, (
        "the resume secret changed. Rotation is what stranded the applicant "
        "whose response was lost -- see the module docstring."
    )


def test_a_request_without_a_key_still_creates_a_new_application(db):
    from app import intake

    payload = _payload(None)
    payload.pop("idempotency_key")
    intake.create_application(payload)
    intake.create_application(payload)

    assert _count(db, "applications") == 2


def test_a_different_key_is_a_different_application(db):
    """Guards the guard: deduplicating everything would pass the first test and
    be catastrophically wrong."""
    from app import intake

    intake.create_application(_payload(f"a-{uuid.uuid4()}"), resume_token=f"client-{uuid.uuid4()}")
    intake.create_application(_payload(f"b-{uuid.uuid4()}"), resume_token=f"client-{uuid.uuid4()}")

    assert _count(db, "applications") == 2


# --- the key alone must not authorise anything -------------------------------

def test_the_key_alone_cannot_recover_an_application(db):
    """The takeover, refused.

    This is the exact call that used to hand back a live access token to anyone
    who knew the key.
    """
    from app import intake

    key = f"takeover-{uuid.uuid4()}"
    # The legitimate client creates the draft with its own secret. That is now
    # required -- see test_a_key_without_a_resume_token_is_refused... -- so the
    # setup supplies one. The attack below is unchanged: someone who learned
    # the key, and only the key.
    intake.create_application(_payload(key), resume_token=f"client-{uuid.uuid4()}")

    with pytest.raises(intake.KeyedRequestNeedsResumeToken):
        intake.create_application(_payload(key))          # no resume token

    # And a guessed token is refused without revealing whether the key is real.
    with pytest.raises(intake.ResumeNotAuthorized):
        intake.create_application(_payload(key), resume_token="guessed-value")


@pytest.mark.parametrize("bad, why", [
    ("guessed-token-value", "guessed"),
    ("x" * 43, "right shape, wrong value"),
    ("almost-right", "plausible but wrong"),
])
def test_a_wrong_token_is_refused(db, bad, why):
    """A token that is present and wrong. Uniform 401 for every reason.

    `None` and `""` used to be in this matrix. They are now refused one step
    earlier and by a different exception, because a keyed request with no token
    would create a row nobody can resume -- so it never reaches the comparison.
    That is a stricter outcome, not a weaker one, and it leaks nothing extra:
    the check runs BEFORE the key is looked up, so the response is identical
    whether or not the key names a real application.
    """
    from app import intake

    key = f"wrong-{uuid.uuid4()}"
    intake.create_application(_payload(key), resume_token=f"client-{uuid.uuid4()}")

    with pytest.raises(intake.ResumeNotAuthorized):
        intake.create_application(_payload(key), resume_token=bad)


@pytest.mark.parametrize("missing", [None, ""])
def test_an_absent_token_is_refused_before_the_key_is_looked_up(db, missing):
    """The absent-token half, and the property that keeps it safe.

    Refusing early could have leaked existence -- "400 if the key is new, 401 if
    it exists" would confirm a guessed key. It does not: the same exception is
    raised for a key that exists and a key that does not.
    """
    from app import intake

    known = f"known-{uuid.uuid4()}"
    intake.create_application(_payload(known), resume_token=f"client-{uuid.uuid4()}")
    unknown = f"unknown-{uuid.uuid4()}"

    for key in (known, unknown):
        with pytest.raises(intake.KeyedRequestNeedsResumeToken):
            intake.create_application(_payload(key), resume_token=missing)


def test_the_secret_is_reusable_but_the_access_token_is_not(db):
    """The trade this design makes, asserted in both directions.

    The old test here demanded the resume token be single-use. That property is
    the reason an applicant whose first response was lost could never recover,
    so it is gone on purpose -- and a test asserting a removed property would
    quietly come back as a re-introduction. What replaces it pins BOTH halves:
    the secret keeps working (recovery survives repeated network failure), and
    the access token -- the credential that actually authorises a decision --
    is fresh every time, so a captured one has a bounded life.
    """
    from app import intake

    key = f"reuse-{uuid.uuid4()}"
    secret = f"client-{uuid.uuid4()}"
    _, access1, _ = intake.create_application(_payload(key), resume_token=secret)
    _, access2, _ = intake.create_application(_payload(key), resume_token=secret)
    _, access3, _ = intake.create_application(_payload(key), resume_token=secret)

    assert access1 != access2 != access3, "the access token was not rotated"

    # And the old one is dead: only the newest hash is stored.
    stored = _row(db, intake.resume_application(key, secret)[0])
    from app import decision_state
    assert stored["access_token_hash"] != decision_state.hash_access_token(access1)


def test_an_expired_token_is_refused(db):
    from app import intake

    key = f"expired-{uuid.uuid4()}"
    app_id, _, resume = intake.create_application(_payload(key), resume_token=f"client-{uuid.uuid4()}")
    with db.cursor() as cur:
        cur.execute(f"SET search_path TO {SCHEMA}")
        cur.execute("UPDATE applications SET resume_token_expires_at = now() - "
                    "interval '1 second' WHERE id = %s", (app_id,))

    with pytest.raises(intake.ResumeNotAuthorized):
        intake.create_application(_payload(key), resume_token=resume)


def test_a_refused_recovery_mints_no_access_token_and_changes_nothing(db):
    """The consequences the contract forbids: no access token, no data, no KYC,
    no decisioning. Asserted on the stored row, because that is what a later
    request would authenticate against."""
    from app import intake

    key = f"nochange-{uuid.uuid4()}"
    app_id, _, _ = intake.create_application(_payload(key), resume_token=f"client-{uuid.uuid4()}")
    before = _row(db, app_id)

    with pytest.raises(intake.ResumeNotAuthorized):
        intake.create_application(_payload(key), resume_token="not-the-token")

    after = _row(db, app_id)
    assert after["access_token_hash"] == before["access_token_hash"], (
        "a refused recovery rotated the access token, so a wrong guess "
        "invalidates the real client's handle -- and a repeated guess is a "
        "denial of service on the applicant"
    )
    assert after["resume_token_hash"] == before["resume_token_hash"]
    assert after["status"] == before["status"]


def test_only_the_hash_of_the_resume_token_is_stored(db):
    from app import intake

    key = f"hash-{uuid.uuid4()}"
    resume = f"client-{uuid.uuid4()}"
    app_id, _, _ = intake.create_application(_payload(key), resume_token=resume)
    row = _row(db, app_id)

    assert row["resume_token_hash"] and row["resume_token_hash"] != resume, (
        "the raw resume token is in the database"
    )
    with db.cursor() as cur:
        cur.execute(f"SET search_path TO {SCHEMA}")
        cur.execute("SELECT count(*) FROM applications WHERE "
                    "resume_token_hash = %s", (resume,))
        assert cur.fetchone()[0] == 0


def test_the_failure_does_not_distinguish_its_reasons(db):
    """Wrong and expired must be indistinguishable.

    Telling them apart tells an attacker which one they achieved -- and
    "expired" in particular confirms the application exists.

    `None` used to be in this set. A keyed request with no token is now refused
    before the key is looked up, so it cannot distinguish anything by
    construction; test_an_absent_token_is_refused_before_the_key_is_looked_up
    asserts that directly, against a key that exists and one that does not.
    """
    from app import intake

    key = f"opaque-{uuid.uuid4()}"
    app_id, _, resume = intake.create_application(_payload(key), resume_token=f"client-{uuid.uuid4()}")

    errors = []
    for bad in ("wrong-value", "another-wrong-value"):
        try:
            intake.create_application(_payload(key), resume_token=bad)
        except intake.ResumeNotAuthorized as e:
            errors.append(repr(e))

    with db.cursor() as cur:
        cur.execute(f"SET search_path TO {SCHEMA}")
        cur.execute("UPDATE applications SET resume_token_expires_at = now() - "
                    "interval '1 second' WHERE id = %s", (app_id,))
    try:
        intake.create_application(_payload(key), resume_token=resume)
    except intake.ResumeNotAuthorized as e:
        errors.append(repr(e))

    assert len(set(errors)) == 1, f"the failures are distinguishable: {set(errors)}"


# --- concurrency --------------------------------------------------------------

def test_a_lost_race_leaves_no_orphan_applicant(db):
    """ON CONFLICT DO NOTHING does not raise -- it returns no row and the
    transaction would COMMIT, leaving an applicant whose application was refused.

    The loser cannot resume without the winner's token, so it raises
    ResumeNotAuthorized -- which is correct: two concurrent first attempts with
    the same key are indistinguishable from an attacker racing a real client, and
    the safe answer to both is "prove it".
    """
    from app import intake

    key = f"race-{uuid.uuid4()}"
    intake.create_application(_payload(key), resume_token=f"client-{uuid.uuid4()}")
    applicants_after_first = _count(db, "applicants")

    real_resume = intake.resume_application
    calls = {"n": 0}

    def _miss_once(k, token=None, fingerprint=None):
        calls["n"] += 1
        return None if calls["n"] == 1 else real_resume(k, token, fingerprint)

    intake.resume_application = _miss_once
    try:
        with pytest.raises(intake.ResumeNotAuthorized):
            intake.create_application(_payload(key), resume_token=f"client-{uuid.uuid4()}")
    finally:
        intake.resume_application = real_resume

    assert _count(db, "applicants") == applicants_after_first, (
        "the losing side of the race committed an applicant with no application"
    )
    assert _count(db, "applications") == 1


# --- the incomplete application still cannot advance -------------------------

def test_an_unverified_application_cannot_be_decided(db):
    from fastapi import HTTPException

    from app import intake
    from app.routers import applications as router

    app_id, _, _ = intake.create_application(_payload(f"undecidable-{uuid.uuid4()}"), resume_token=f"client-{uuid.uuid4()}")

    with pytest.raises(HTTPException) as excinfo:
        router._require_persisted_kyc(app_id)

    assert excinfo.value.status_code == 409
    assert "identity verification" in str(excinfo.value.detail).lower()


def test_two_simultaneous_resumes_both_succeed_and_both_stay_recoverable(db):
    """The race the compare-and-swap closes, restated for a stable secret.

    This test used to demand exactly ONE winner. That was the right property
    while the resume token rotated: the loser's caller walked away holding an
    access token whose resume token had been rotated away by its twin, and it
    could never recover -- it had no credential left to try again with. A
    borrower double-submitting their browser needed support.

    With a client-held secret the harm is gone rather than hidden. Both resumes
    match the WHERE clause and both succeed. The access token still rotates, so
    last-write-wins and one caller may hold a stale one -- but that caller
    *still holds the secret*, so it resumes again and gets a live token. An
    unrecoverable state became a retryable one.

    Two real connections, fired at a barrier, because the guarantee is a WHERE
    clause evaluated under a row lock and a single-threaded test cannot observe it.
    """
    import threading

    from app import decision_state, intake

    key = f"concurrent-{uuid.uuid4()}"
    resume = f"client-{uuid.uuid4()}"
    app_id, _, _ = intake.create_application(_payload(key), resume_token=resume)

    barrier = threading.Barrier(2)
    results, errors = [], []

    def _resume():
        try:
            barrier.wait(timeout=10)
            results.append(intake.resume_application(key, resume))
        except intake.ResumeNotAuthorized:
            errors.append("refused")
        except Exception as e:                              # pragma: no cover
            errors.append(repr(e))

    threads = [threading.Thread(target=_resume) for _ in range(2)]
    for t in threads:
        t.start()
    for t in threads:
        t.join(timeout=20)

    assert errors == [], f"a concurrent resume failed: {errors}"
    winners = [r for r in results if r]
    assert len(winners) == 2, "a legitimate concurrent retry was refused"
    assert {w[0] for w in winners} == {app_id}, "the retries recovered different applications"

    # Exactly one access token authenticates -- the writes serialised under the
    # row lock rather than interleaving into a torn state.
    row = _row(db, app_id)
    live = [w for w in winners
            if row["access_token_hash"] == decision_state.hash_access_token(w[1])]
    assert len(live) == 1, (
        "the row does not authenticate exactly one of the two issued access "
        "tokens, so the two rotations interleaved"
    )

    # The point: the caller holding the stale token is not stranded. It has the
    # secret, so it resumes again and gets a token that works.
    recovered = intake.resume_application(key, resume)
    assert recovered is not None
    assert _row(db, app_id)["access_token_hash"] ==         decision_state.hash_access_token(recovered[1])

    # And the secret itself is untouched by any of it.
    assert _row(db, app_id)["resume_token_hash"] ==         decision_state.hash_access_token(resume)


def test_the_rotation_is_a_single_statement(db):
    """Derived, because "validate then update" is the shape of the defect and it
    reads as correct. A future refactor that splits them again fails here."""
    import inspect

    from app import intake

    src = inspect.getsource(intake.resume_application)
    assert "UPDATE applications SET" in src and "AND resume_token_hash = %s" in src, (
        "the rotation no longer validates the token inside the UPDATE's WHERE "
        "clause, so validation and mutation are two statements again"
    )
    assert "resume_token_expires_at > now()" in src, (
        "expiry is not checked inside the compare-and-swap"
    )


# --- the lost first response: the failure this whole contract exists for ------

def test_retry_after_a_lost_response_returns_the_same_application(db):
    """The exact reported scenario, end to end."""
    from app import intake

    key = str(uuid.uuid4())
    client_secret = str(uuid.uuid4())

    # First submission commits. Its response is then dropped on the floor --
    # the client learns nothing from it, so the test keeps only the app_id to
    # assert against later, and NOT the tokens.
    first_id, _lost_access, _lost_resume = intake.create_application(
        _payload(key), resume_token=client_secret
    )

    # The retry. The client presents what it has always had: its own secret.
    recovered = intake.resume_application(key, client_secret)

    assert recovered is not None, (
        "the applicant was refused their own in-flight application after a lost "
        "response -- they are now forced to create a duplicate"
    )
    assert recovered[0] == first_id


def test_the_returned_secret_is_the_clients_own_not_a_new_one(db):
    """Rotation would rebuild the hole one attempt later.

    If recovery handed back a NEW secret, the client would have to receive the
    SECOND response to stay recoverable -- the same single point of failure,
    moved. So the value echoed back must be the caller's own.
    """
    from app import intake

    key, secret = str(uuid.uuid4()), str(uuid.uuid4())
    intake.create_application(_payload(key), resume_token=secret)

    _id, _access, returned = intake.resume_application(key, secret)
    assert returned == secret

    # And it still works the next time, and the time after that. A client that
    # loses two responses in a row is not locked out either.
    for _ in range(3):
        again = intake.resume_application(key, secret)
        assert again is not None and again[0] == _id


def test_the_secret_never_reaches_the_database_in_the_clear(db):
    """Client-generated does not mean stored raw."""
    from app import intake

    key, secret = str(uuid.uuid4()), str(uuid.uuid4())
    intake.create_application(_payload(key), resume_token=secret)

    rows = _query(db, 
        "SELECT resume_token_hash FROM applications WHERE idempotency_key = %s",
        (key,),
    )
    stored = rows[0]["resume_token_hash"]
    assert stored and stored != secret
    assert secret not in str(rows)


def test_a_wrong_secret_is_still_refused(db):
    """Recovery must not have become a free pass in the course of fixing this."""
    from app import intake

    key = str(uuid.uuid4())
    intake.create_application(
        _payload(key), resume_token=str(uuid.uuid4())
    )

    with pytest.raises(intake.ResumeNotAuthorized):
        intake.resume_application(key, str(uuid.uuid4()))
    with pytest.raises(intake.ResumeNotAuthorized):
        intake.resume_application(key, None)


def test_an_unknown_key_is_a_create_not_a_refusal(db):
    """The ordinary first attempt: no application, so nothing to authorise."""
    from app import intake

    assert intake.resume_application(str(uuid.uuid4()), None) is None
    assert intake.resume_application(str(uuid.uuid4()), str(uuid.uuid4())) is None


def test_the_server_does_not_mint_resume_tokens_anywhere(db):
    """A source check, because a reintroduction would pass every test above.

    Re-adding a server-minted token would not break the cases here -- they would
    keep passing while the lost-response hole was back. What actually holds the
    property is that no server code path generates this credential at all.
    """
    from app import intake

    import pathlib

    source = pathlib.Path(intake.__file__).read_text(encoding="utf-8")
    minting = [
        line.strip()
        for line in source.splitlines()
        if "new_resume_token" in line and not line.strip().startswith("#")
    ]
    assert not minting, (
        "the origination service mints a resume token again: "
        f"{minting}. A credential invented by the server is one the client "
        "does not have when the response is lost."
    )


# --- what a stale credential actually costs -----------------------------------

def test_a_stale_credential_from_another_applicant_is_now_refused(db):
    """The cross-applicant exposure, closed a second time.

    This test used to DOCUMENT the blast radius: with a stale key and secret
    left in a shared browser, a second person's submission returned the first
    person's application and a live access token for it, and their own payload
    was discarded. The frontend fix cleared the credentials on intake success so
    the pairing could not arise.

    The fingerprint closes it from the server side as well, which matters
    because the client fix depends on the client. A different applicant is a
    different payload, so the retry is refused outright -- no application, no
    token, nothing to leak. Defence in depth: either fix alone would do, and
    neither has to be trusted on its own.
    """
    from app import intake

    key, secret = f"stale-{uuid.uuid4()}", f"client-{uuid.uuid4()}"

    alice = _payload(key)
    alice["name"] = "Alice Applicant"
    alice["email"] = "alice@example.test"
    alice["amount"] = 9000
    first_id, _, _ = intake.create_application(alice, resume_token=secret)

    bob = _payload(key)
    bob["name"] = "Bob Different"
    bob["email"] = "bob@example.test"
    bob["ssn"] = "999-00-0099"
    bob["dob"] = "1990-07-04"
    bob["amount"] = 31000

    with pytest.raises(intake.RetryPayloadMismatch):
        intake.create_application(bob, resume_token=secret)

    # Alice's application is untouched, and Bob got nothing at all.
    stored = _query(
        db,
        "SELECT ap.name, ap.email, a.amount FROM applications a "
        "JOIN applicants ap ON ap.id = a.applicant_id WHERE a.id = %s",
        (first_id,),
    )[0]
    assert stored["name"] == "Alice Applicant"
    assert stored["amount"] == 9000
    assert _query(db, "SELECT id FROM applicants WHERE name = %s",
                  ("Bob Different",)) == []


# --- a keyed request must carry its recovery secret ---------------------------

def test_a_key_without_a_resume_token_is_refused_before_anything_is_written(db):
    """The unrecoverable row, refused at the door.

    `idempotency_key` and `X-Resume-Token` were independently optional, so a key
    with no token stored `resume_token_hash = NULL`. If KYC then failed, the 503
    handed back `resume_token: null`, the retry found the application, had
    nothing to authorise with, and was refused -- leaving a recorded application
    reachable only through support or a database repair.

    The assertion that matters is the second one: nothing was written.
    """
    from app import intake

    key = f"nokey-{uuid.uuid4()}"
    before_applicants = _count(db, "applicants")
    before_applications = _count(db, "applications")

    with pytest.raises(intake.KeyedRequestNeedsResumeToken):
        intake.create_application(_payload(key), resume_token=None)

    assert _count(db, "applicants") == before_applicants, (
        "an applicant row was written for a request that was refused"
    )
    assert _count(db, "applications") == before_applications
    assert _query(db, "SELECT id FROM applications WHERE idempotency_key = %s",
                  (key,)) == []


def test_a_request_with_no_key_at_all_is_still_allowed(db):
    """The rule is that the two travel together, not that a token is mandatory.

    An unkeyed submission has no retry contract to honour and must keep working
    -- otherwise this fix breaks every caller that never opted in.
    """
    from app import intake

    app_id, access, resume = intake.create_application(_payload(None), resume_token=None)
    assert app_id and access
    assert resume is None


# --- a retry may not quietly change the applicant -----------------------------

def _changed(key, **overrides):
    payload = _payload(key)
    payload.update(overrides)
    return payload


@pytest.mark.parametrize("field,value", [
    ("ssn", "999-00-1234"),
    ("dob", "1979-01-02"),
    ("name", "Someone Else"),
    ("address", "9 Different Road"),
    ("zip_code", "10001"),
    ("income", 250000),
    ("amount", 45000),
    ("term_months", 60),
])
def test_a_retry_that_changes_identity_or_underwriting_is_refused(db, field, value):
    """409, not the stored copy.

    The browser deliberately keeps the retry credentials after a failed
    submission so the borrower CAN correct a mistake. So this is the ordinary
    path for someone fixing a mistyped SSN or income -- and the old behaviour
    returned the original application, then ran KYC and decisioning against the
    value they had just corrected. The corrected number is visible in their own
    form and absent from the decision.
    """
    from app import intake

    key, secret = f"changed-{uuid.uuid4()}", f"client-{uuid.uuid4()}"
    intake.create_application(_payload(key), resume_token=secret)

    with pytest.raises(intake.RetryPayloadMismatch):
        intake.create_application(_changed(key, **{field: value}), resume_token=secret)


def test_an_identical_retry_is_still_accepted(db):
    """The other direction, and the one that would break the product.

    A borrower retrying the identical form must not be told their details
    changed. If this fails, every legitimate retry now 409s.
    """
    from app import intake

    key, secret = f"same-{uuid.uuid4()}", f"client-{uuid.uuid4()}"
    first_id, _, _ = intake.create_application(_payload(key), resume_token=secret)
    again_id, _, _ = intake.create_application(_payload(key), resume_token=secret)

    assert again_id == first_id
    assert _count(db, "applicants") == 1


def test_cosmetic_differences_do_not_count_as_a_changed_request(db):
    """Whitespace and case are not a different applicant.

    A fingerprint over raw values would 409 a borrower whose browser trimmed a
    trailing space -- a false rejection on the retry path, which is worse than
    the bug being fixed because it has no workaround.
    """
    from app import intake

    key, secret = f"cosmetic-{uuid.uuid4()}", f"client-{uuid.uuid4()}"
    first_id, _, _ = intake.create_application(_payload(key), resume_token=secret)

    noisy = _payload(key)
    noisy["name"] = f"  {noisy['name'].upper()}  "
    noisy["email"] = noisy["email"].upper()
    again_id, _, _ = intake.create_application(noisy, resume_token=secret)

    assert again_id == first_id


def test_a_row_written_before_the_fingerprint_existed_stays_resumable(db):
    """The upgrade path.

    Rows created before migration 0038 have request_fingerprint = NULL. They
    must remain recoverable -- an in-flight application must not be stranded by
    a deploy. NULL means "cannot verify", which is exactly the pre-migration
    behaviour and no worse than it.
    """
    from app import intake

    key, secret = f"legacy-{uuid.uuid4()}", f"client-{uuid.uuid4()}"
    app_id, _, _ = intake.create_application(_payload(key), resume_token=secret)

    with db.cursor() as cur:
        cur.execute(f"SET search_path TO {SCHEMA}")
        cur.execute("UPDATE applications SET request_fingerprint = NULL WHERE id = %s",
                    (app_id,))

    # Even a CHANGED payload is accepted, because there is nothing to compare
    # against. Asserted explicitly so the compatibility rule is visible rather
    # than incidental.
    again_id, _, _ = intake.create_application(
        _changed(key, income=999999), resume_token=secret)
    assert again_id == app_id


def test_the_fingerprint_covers_every_identity_and_underwriting_field(db):
    """Derived, not hand-checked.

    A field left out of the tuple is a field a retry can change silently, and
    that omission is invisible in a test that only exercises the fields someone
    remembered. This enumerates the tuple itself.
    """
    from app import intake

    base = _payload("fp")
    baseline = intake._request_fingerprint(base)

    for field in intake._FINGERPRINTED_FIELDS:
        mutated = dict(base)
        current = mutated.get(field)
        mutated[field] = "ZZ-different" if not isinstance(current, (int, float)) else (current or 0) + 7
        assert intake._request_fingerprint(mutated) != baseline, (
            f"changing {field!r} does not change the fingerprint, so a retry "
            f"could alter it without detection"
        )


def test_the_stored_fingerprint_is_a_digest_not_the_payload(db):
    """It is computed over the SSN, so it must not be reversible to it."""
    from app import intake

    key, secret = f"digest-{uuid.uuid4()}", f"client-{uuid.uuid4()}"
    payload = _payload(key)
    intake.create_application(payload, resume_token=secret)

    row = _query(db, "SELECT request_fingerprint FROM applications "
                     "WHERE idempotency_key = %s", (key,))[0]
    stored = row["request_fingerprint"]
    assert stored and len(stored) == 64
    assert payload["ssn"] not in stored
    assert payload["name"].lower() not in stored.lower()
